executors:
  mac:
    working_directory: ~/SalesforceMobileSDK-iOS-Hybrid
    macos:
      xcode: "10.3.0"
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashrc
      FASTLANE_SKIP_UPDATE_CHECK: true
      CHRUBY_VER: 2.6.3

version: 2.1
jobs:
  run-tests:
    executor: mac
    parameters:
      lib:
        type: string
        default: "SalesforceHybridSDK"
      device:
        type: string
        default: "iPhone XR"
      ios:
        type: string
        default: "12.4"
    environment:
      DEVICE: << parameters.device >>
      IOS_VERSION: << parameters.ios >>
    steps:
      - checkout
      - restore_cache: 
          key: v5-gems-{{ checksum ".circleci/Gemfile.lock" }}
      - run: 
          name: Installing gem dependencies
          command:  |
            ./install.sh
            ./build/pre-build
            chruby ${CHRUBY_VER}
            cd .circleci
            bundle check || bundle install
            bundle update
      - save_cache: 
          key: v5-gems-{{ checksum ".circleci/Gemfile.lock" }}
          paths:
            - /Users/distiller/.gem/ruby/${CHRUBY_VER}
            - /Users/distiller/.rubies/ruby-2.4.5/lib/ruby/gems/${CHRUBY_VER}
      - run: 
          name: Setting up workspace
          command:  |
            ./install.sh
            ./build/pre-build
      - run: 
          name: Compile
          command:  |
            chruby ${CHRUBY_VER}
            cd .circleci
            fastlane build lib:<< parameters.lib >>
      - run: 
            name: Run Tests
            command:  |
              chruby ${CHRUBY_VER}
              cd .circleci
              fastlane test lib:<< parameters.lib >>
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/test_output
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/test_output
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/clangReport
          destination: Static-Analysis
      - run: 
          name: Upload code coverage
          command: bash <(curl -s https://codecov.io/bash) -X gcov -X xcode
          when: always

workflows:
  version: 2

  pr-test-hybrid:
    jobs:
      - run-tests:
          name: "SalesforceHybridSDK"
      - run-tests:
          name: "SalesforceFileLogger"
          lib: "SalesforceFileLogger"  

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything at ~10:30pm Sunday/Wednesday Nights
  nightly-test-hybrid:
    triggers:
      - schedule:
          cron: "30 6 * * 1,4"
          filters:
            branches:
              only:
                - dev
    jobs:
      - run-tests:
          name: "SalesforceHybridSDK Nightly"
      - run-tests:
          name: "SalesforceFileLogger Nightly"
          lib: "SalesforceFileLogger"  

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything at ~11:30pm Sunday/Wednesday Nights
  nightly-test-hybrid-iOS11:
    triggers:
      - schedule:
          cron: "30 7 * * 1,4"
          filters:
            branches:
              only:
                - dev
    jobs:
      - run-tests:
          name: "SalesforceHybridSDK iOS 11 Nightly"
          device: "iPhone X"
          ios: "11.4"
      - run-tests:
          name: "SalesforceFileLogger iOS 11 Nightly"
          lib: "SalesforceFileLogger"  
          device: "iPhone X"
          ios: "11.4"