aliases:
  - &restore-gem-cache
    key: v5-gems-{{ checksum ".circleci/Gemfile.lock" }}
    paths:
      - /Users/distiller/.gem/ruby/2.5.1
      - /Users/distiller/.rubies/ruby-2.4.2/lib/ruby/gems/2.5.1

  - &save-gem-cache
    key: v5-gems-{{ checksum ".circleci/Gemfile.lock" }}

  - &install-dependencies
    name: Installing gem dependencies
    command:  |
      ./install.sh
      ./build/pre-build
      chruby ${CHRUBY_VER}
      cd .circleci
      gem install bundler
      bundle check || bundle install
      bundle update

  - &compile
    name: Compile
    command:  |
      chruby ${CHRUBY_VER}
      cd .circleci
      fastlane "build lib:${SCHEME}"

  - &run-tests
    name: Run Tests
    command:  |
      chruby ${CHRUBY_VER}
      cd .circleci
      fastlane "test lib:${SCHEME}"
  
  - &upload-codecov
    name: Upload code coverage
    command: bash <(curl -s https://codecov.io/bash) -X gcov -X xcode
    when: always

defaults: &defaults
  working_directory: ~/SalesforceMobileSDK-iOS-Hybrid
  macos:
    xcode: "10.0.0"
  shell: /bin/bash --login -eo pipefail
  environment:
    BASH_ENV: ~/.bashrc
    FASTLANE_SKIP_UPDATE_CHECK: true
    CHRUBY_VER: 2.5.1

version: 2
jobs:
  SalesforceHybridSDK:
    <<: *defaults
    environment:
      - SCHEME: "SalesforceHybridSDK"
    steps:
      - checkout
      - restore_cache: *restore-gem-cache
      - run: *install-dependencies
      - save_cache: *save-gem-cache
      - run: *compile
      - run: *run-tests
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/test_output
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/test_output
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/clangReport
          destination: Static-Analysis
      - run: *upload-codecov

  SalesforceFileLogger:
    <<: *defaults
    environment:
      - SCHEME: "SalesforceFileLogger"
    steps:
      - checkout
      - restore_cache: *restore-gem-cache
      - run: *install-dependencies
      - save_cache: *save-gem-cache
      - run: *compile
      - run: *run-tests
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/test_output
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/test_output
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/clangReport
          destination: Static-Analysis
      - run: *upload-codecov

workflows:
  version: 2

  pr-build-all-apps:
    jobs:
      - SalesforceHybridSDK
      - SalesforceFileLogger

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything at ~10:30pm Sunday/Wednesday Nights
  weekly-build-all-apps:
    triggers:
      - schedule:
          cron: "30 6 * * 1,4"
          filters:
            branches:
              only:
                - dev

    jobs:
      - SalesforceHybridSDK
      - SalesforceFileLogger
