#  Xcode version announcments can be found here: https://discuss.circleci.com/c/announcements/
#  Each post contains a full image manifest, including iOS runtimes, devices, CocoaPods version, etc.
#  NOTE: When updaing Xcode check the manifest for compatible chruby versions.
anchors:
  - &latest-xcode "13.4.1"
  - &beta-xcode   "14.0.0"
  - &latest-ios   "15.5"
  - &min-ios      "14.5"
  - &beta-ios     "16.0"
  - &chruby       "3.1.2"

executors:
  mac:
    working_directory: ~/SalesforceMobileSDK-iOS-Hybrid
    macos:
      xcode: *latest-xcode
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashrc
      FASTLANE_SKIP_UPDATE_CHECK: "true"
      CHRUBY_VER: *chruby
  mac-beta:
    working_directory: ~/SalesforceMobileSDK-iOS-Hybrid
    macos:
      xcode: *beta-xcode
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashrc
      FASTLANE_SKIP_UPDATE_CHECK: "true"
      CHRUBY_VER: *chruby


version: 2.1
jobs:
  run-tests:
    parameters:
      lib:
        type: string
        default: "SalesforceHybridSDK"
      device:
        type: string
        default: "iPhone 12"
      ios:
        type: string
        default: *latest-ios
      lane:
        type: string
        default: "test"
      env: 
        type: executor
        default: "mac"
    executor: << parameters.env >> 
    environment:
      LIB: << parameters.lib >> 
      DEVICE: << parameters.device >>
      IOS_VERSION: << parameters.ios >>
    steps:
      - checkout
      - restore_cache: 
          key: v6-gems-{{ checksum ".circleci/Gemfile.lock" }}
      - run: 
          name: Installing gem dependencies
          command:  |
            npm install shelljs@0.8.5
            ./install.sh
            ./build/pre-build
            cd .circleci
            chruby ${CHRUBY_VER}
            sudo bundle update --bundler
            bundle check || sudo bundle install
            sudo bundle update
      - save_cache: 
          key: v6-gems-{{ checksum ".circleci/Gemfile.lock" }}
          paths:
            - /Users/distiller/.gem/ruby/${CHRUBY_VER}
      - run: 
          name: Compile
          command:  |
            chruby ${CHRUBY_VER}
            cd .circleci
            bundle exec fastlane build lib:<< parameters.lib >> 
      - run: 
            name: Run Tests
            command:  |
              chruby ${CHRUBY_VER}
              cd .circleci
              fastlane << parameters.lane >> lib:<< parameters.lib >>
      - run: 
          name: Danger Lib
          command:  |
            chruby ${CHRUBY_VER}
            DANGER_GITHUB_API_TOKEN="279a29d75427e4178cef""b7b5b2d7646c540f025a" danger --dangerfile=.circleci/Dangerfile-Lib.rb --danger_id="${LIB}" --verbose
          background: true
          when: always
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/test_output
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/test_output
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/clangReport
          destination: Static-Analysis

#  Potential parameters that can come from the project GUI Triggers
parameters:
  run-schedule:
    type: boolean
    default: false
  beta:
    type: boolean
    default: false

workflows:
  version: 2

  pr-test-hybrid:
    jobs:
      - run-tests:
          matrix:
            parameters:
              lib: ["SalesforceHybridSDK", "SalesforceFileLogger"]
              lane: ["PR"]
          filters:
            branches:
              only:
                - /pull.*/

  # Build everything at ~10 PM PST Sunday/Wednesday Nights
  hybrid-iOS:
    when: 
      and:
        - << pipeline.parameters.run-schedule >>
        - equal: [ false, << pipeline.parameters.beta >> ]
    jobs:
      - run-tests:
          name: test << matrix.lib >> iOS << matrix.ios >>
          matrix:
            parameters:
              lib: ["SalesforceHybridSDK", "SalesforceFileLogger"]
              ios: [*min-ios, *latest-ios]

  # Build everything at ~11 PM PST Sunday/Wednesday Nights
  hybrid-iOS-beta:
    when: 
      and:
        - << pipeline.parameters.run-schedule >>
        - << pipeline.parameters.beta >>
    jobs:
      - run-tests:
          name: test << matrix.lib >> iOS << matrix.ios >>
          matrix:
            parameters:
              lib: ["SalesforceHybridSDK", "SalesforceFileLogger"]
              ios: [*beta-ios]
              device: ["iPhone 13"]
              env: ["mac-beta"]